name: Windows

on:
  push:
    branches:
      - main

jobs:

  build-executable:
    name: Build Windows executable
    runs-on: windows-2019

    steps:
      - name: Chekout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-live.txt
          pip install ".[dev,gui]"

      - name: Linting with ruff
        uses: chartboost/ruff-action@v1

      - name: Test with pytest
        run: |
          pip install pytest pytest-qt pytest-xvfb
          pytest

      - name: Build executable
        run: |
          pip install pyinstaller setuptools-git-versioning
          VERSION=$(setuptools-git-versioning)
          PLAT=$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')
          ARCH=$(echo ${{ runner.arch }} | tr '[:upper:]' '[:lower:]')
          echo ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
          echo $VERSION $PLAT $ARCH
          setuptools-git-versioning
          echo ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
          sh ./scripts/pack/make-executable.sh $VERSION $PLAT $ARCH

      - uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: dist/*.exe
