name: Windows

on:
  push:
    branches:
      - main

jobs:

  build-executable:
    name: Build Windows executable
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-live.txt
          pip install ".[dev,gui]"

      - name: Linting with ruff
        uses: chartboost/ruff-action@v1

      - name: Test with pytest
        run: |
          pip install pytest pytest-qt pytest-xvfb
          pytest

      - name: Build executable
        uses: ./.github/actions/make-executable

      - uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: dist/*.exe
